
<!-- begin of generated class -->
<?php
/*
*
* -------------------------------------------------------
* CLASSNAME:        usa
* GENERATION DATE:  28.04.2011
* CLASS FILE:       C:\xampp\htdocs\sql_class_generator-2006-01-02/generated_classes/class.usa.php
* FOR MYSQL TABLE:  usuarios
* FOR MYSQL DB:     demoabm
* -------------------------------------------------------
* CODE GENERATED BY:
* MY PHP-MYSQL-CLASS GENERATOR
* from: >> www.voegeli.li >> (download for free!)
* -------------------------------------------------------
*
*/

include_once("resources/class.database.php");

// **********************
// CLASS DECLARATION
// **********************

class usa
{ // class : begin


// **********************
// ATTRIBUTE DECLARATION
// **********************

var $1;   // KEY ATTR. WITH AUTOINCREMENT

var $id;   // (normal Attribute)
var $usuario;   // (normal Attribute)
var $pass;   // (normal Attribute)
var $nivel;   // (normal Attribute)
var $fechaAlta;   // (normal Attribute)
var $ip;   // (normal Attribute)
var $activo;   // (normal Attribute)
var $ultimoLogin;   // (normal Attribute)
var $email;   // (normal Attribute)
var $nombre;   // (normal Attribute)
var $apellido;   // (normal Attribute)
var $paisId;   // (normal Attribute)
var $comentarios;   // (normal Attribute)

var $database; // Instance of class database


// **********************
// CONSTRUCTOR METHOD
// **********************

function usa()
{

$this->database = new Database();

}


// **********************
// GETTER METHODS
// **********************


function getid()
{
return $this->id;
}

function getusuario()
{
return $this->usuario;
}

function getpass()
{
return $this->pass;
}

function getnivel()
{
return $this->nivel;
}

function getfechaAlta()
{
return $this->fechaAlta;
}

function getip()
{
return $this->ip;
}

function getactivo()
{
return $this->activo;
}

function getultimoLogin()
{
return $this->ultimoLogin;
}

function getemail()
{
return $this->email;
}

function getnombre()
{
return $this->nombre;
}

function getapellido()
{
return $this->apellido;
}

function getpaisId()
{
return $this->paisId;
}

function getcomentarios()
{
return $this->comentarios;
}

// **********************
// SETTER METHODS
// **********************


function setid($val)
{
$this->id =  $val;
}

function setusuario($val)
{
$this->usuario =  $val;
}

function setpass($val)
{
$this->pass =  $val;
}

function setnivel($val)
{
$this->nivel =  $val;
}

function setfechaAlta($val)
{
$this->fechaAlta =  $val;
}

function setip($val)
{
$this->ip =  $val;
}

function setactivo($val)
{
$this->activo =  $val;
}

function setultimoLogin($val)
{
$this->ultimoLogin =  $val;
}

function setemail($val)
{
$this->email =  $val;
}

function setnombre($val)
{
$this->nombre =  $val;
}

function setapellido($val)
{
$this->apellido =  $val;
}

function setpaisId($val)
{
$this->paisId =  $val;
}

function setcomentarios($val)
{
$this->comentarios =  $val;
}

// **********************
// SELECT METHOD / LOAD
// **********************

function select($id)
{

$sql =  "SELECT * FROM usuarios WHERE 1 = $id;";
$result =  $this->database->query($sql);
$result = $this->database->result;
$row = mysql_fetch_object($result);


$this->id = $row->id;

$this->usuario = $row->usuario;

$this->pass = $row->pass;

$this->nivel = $row->nivel;

$this->fechaAlta = $row->fechaAlta;

$this->ip = $row->ip;

$this->activo = $row->activo;

$this->ultimoLogin = $row->ultimoLogin;

$this->email = $row->email;

$this->nombre = $row->nombre;

$this->apellido = $row->apellido;

$this->paisId = $row->paisId;

$this->comentarios = $row->comentarios;

}

// **********************
// DELETE
// **********************

function delete($id)
{
$sql = "DELETE FROM usuarios WHERE 1 = $id;";
$result = $this->database->query($sql);

}

// **********************
// INSERT
// **********************

function insert()
{
$this->1 = ""; // clear key for autoincrement

$sql = "INSERT INTO usuarios ( id,usuario,pass,nivel,fechaAlta,ip,activo,ultimoLogin,email,nombre,apellido,paisId,comentarios ) VALUES ( '$this->id','$this->usuario','$this->pass','$this->nivel','$this->fechaAlta','$this->ip','$this->activo','$this->ultimoLogin','$this->email','$this->nombre','$this->apellido','$this->paisId','$this->comentarios' )";
$result = $this->database->query($sql);
$this->1 = mysql_insert_id($this->database->link);

}

// **********************
// UPDATE
// **********************

function update($id)
{



$sql = " UPDATE usuarios SET  id = '$this->id',usuario = '$this->usuario',pass = '$this->pass',nivel = '$this->nivel',fechaAlta = '$this->fechaAlta',ip = '$this->ip',activo = '$this->activo',ultimoLogin = '$this->ultimoLogin',email = '$this->email',nombre = '$this->nombre',apellido = '$this->apellido',paisId = '$this->paisId',comentarios = '$this->comentarios' WHERE 1 = $id ";

$result = $this->database->query($sql);



}


} // class : end

?>
<!-- end of generated class -->
