
<!-- begin of generated class -->
<?php
/*
*
* -------------------------------------------------------
* CLASSNAME:        rowsxproductos
* GENERATION DATE:  18.08.2011
* CLASS FILE:       C:\xampp\htdocs\class_generator/generated_classes/class.rowsxproductos.php
* FOR MYSQL TABLE:  rowsxproductos
* FOR MYSQL DB:     contenidos
* -------------------------------------------------------
* CODE GENERATED BY:
* MY PHP-MYSQL-CLASS GENERATOR
* from: >> www.voegeli.li >> (download for free!)
* -------------------------------------------------------
*
*/

include_once("resources/class.database.php");

// **********************
// CLASS DECLARATION
// **********************

class rowsxproductos
{ // class : begin


// **********************
// ATTRIBUTE DECLARATION
// **********************

var $idRow,idTipoRow;   // KEY ATTR. WITH AUTOINCREMENT

var $idRow;   // (normal Attribute)
var $idTipoRow;   // (normal Attribute)
var $idCatalogo;   // (normal Attribute)
var $IdSitio;   // (normal Attribute)

var $database; // Instance of class database


// **********************
// CONSTRUCTOR METHOD
// **********************

function rowsxproductos()
{

$this->database = new Database();

}


// **********************
// GETTER METHODS
// **********************


function getidRow()
{
return $this->idRow;
}

function getidTipoRow()
{
return $this->idTipoRow;
}

function getidCatalogo()
{
return $this->idCatalogo;
}

function getIdSitio()
{
return $this->IdSitio;
}

// **********************
// SETTER METHODS
// **********************


function setidRow($val)
{
$this->idRow =  $val;
}

function setidTipoRow($val)
{
$this->idTipoRow =  $val;
}

function setidCatalogo($val)
{
$this->idCatalogo =  $val;
}

function setIdSitio($val)
{
$this->IdSitio =  $val;
}

// **********************
// SELECT METHOD / LOAD
// **********************

function select($id)
{

$sql =  "SELECT * FROM rowsxproductos WHERE idRow,idTipoRow = $id;";
$result =  $this->database->query($sql);
$result = $this->database->result;
$row = mysql_fetch_object($result);


$this->idRow = $row->idRow;

$this->idTipoRow = $row->idTipoRow;

$this->idCatalogo = $row->idCatalogo;

$this->IdSitio = $row->IdSitio;

}

// **********************
// DELETE
// **********************

function delete($id)
{
$sql = "DELETE FROM rowsxproductos WHERE idRow,idTipoRow = $id;";
$result = $this->database->query($sql);

}

// **********************
// INSERT
// **********************

function insert()
{
$this->idRow,idTipoRow = ""; // clear key for autoincrement

$sql = "INSERT INTO rowsxproductos ( idRow,idTipoRow,idCatalogo,IdSitio ) VALUES ( '$this->idRow','$this->idTipoRow','$this->idCatalogo','$this->IdSitio' )";
$result = $this->database->query($sql);
$this->idRow,idTipoRow = mysql_insert_id($this->database->link);

}

// **********************
// UPDATE
// **********************

function update($id)
{



$sql = " UPDATE rowsxproductos SET  idRow = '$this->idRow',idTipoRow = '$this->idTipoRow',idCatalogo = '$this->idCatalogo',IdSitio = '$this->IdSitio' WHERE idRow,idTipoRow = $id ";

$result = $this->database->query($sql);



}


} // class : end

?>
<!-- end of generated class -->
