
<!-- begin of generated class -->
<?php
/*
*
* -------------------------------------------------------
* CLASSNAME:        prestaciones
* GENERATION DATE:  30.05.2011
* CLASS FILE:       C:\xampp\htdocs\sql_class_generator-2006-01-02/generated_classes/class.prestaciones.php
* FOR MYSQL TABLE:  prestaciones
* FOR MYSQL DB:     contenidos
* -------------------------------------------------------
* CODE GENERATED BY:
* MY PHP-MYSQL-CLASS GENERATOR
* from: >> www.voegeli.li >> (download for free!)
* -------------------------------------------------------
*
*/

include_once("resources/class.database.php");

// **********************
// CLASS DECLARATION
// **********************

class prestaciones
{ // class : begin


// **********************
// ATTRIBUTE DECLARATION
// **********************

var $idPrestaciones;   // KEY ATTR. WITH AUTOINCREMENT

var $Titulo;   // (normal Attribute)
var $Icono;   // (normal Attribute)
var $Link;   // (normal Attribute)
var $Orden;   // (normal Attribute)

var $database; // Instance of class database


// **********************
// CONSTRUCTOR METHOD
// **********************

function prestaciones()
{

$this->database = new Database();

}


// **********************
// GETTER METHODS
// **********************


function getidPrestaciones()
{
return $this->idPrestaciones;
}

function getTitulo()
{
return $this->Titulo;
}

function getIcono()
{
return $this->Icono;
}

function getLink()
{
return $this->Link;
}

function getOrden()
{
return $this->Orden;
}

// **********************
// SETTER METHODS
// **********************


function setidPrestaciones($val)
{
$this->idPrestaciones =  $val;
}

function setTitulo($val)
{
$this->Titulo =  $val;
}

function setIcono($val)
{
$this->Icono =  $val;
}

function setLink($val)
{
$this->Link =  $val;
}

function setOrden($val)
{
$this->Orden =  $val;
}

// **********************
// SELECT METHOD / LOAD
// **********************

function select($id)
{

$sql =  "SELECT * FROM prestaciones WHERE idPrestaciones = $id;";
$result =  $this->database->query($sql);
$result = $this->database->result;
$row = mysql_fetch_object($result);


$this->idPrestaciones = $row->idPrestaciones;

$this->Titulo = $row->Titulo;

$this->Icono = $row->Icono;

$this->Link = $row->Link;

$this->Orden = $row->Orden;

}

// **********************
// SELECT METHOD / LOAD
// **********************

function selectAll()
{

$sql =  "SELECT * FROM prestaciones Order by Orden";
$result =  $this->database->query($sql);
$result = $this->database->result;
$row = mysql_fetch_object($result);


$this->idPrestaciones = $row->idPrestaciones;

$this->Titulo = $row->Titulo;

$this->Icono = $row->Icono;

$this->Link = $row->Link;

$this->Orden = $row->Orden;

}





// **********************
// DELETE
// **********************

function delete($id)
{
$sql = "DELETE FROM prestaciones WHERE idPrestaciones = $id;";
$result = $this->database->query($sql);

}

// **********************
// INSERT
// **********************

function insert()
{
$this->idPrestaciones = ""; // clear key for autoincrement

$sql = "INSERT INTO prestaciones ( Titulo,Icono,Link,Orden ) VALUES ( '$this->Titulo','$this->Icono','$this->Link','$this->Orden' )";
$result = $this->database->query($sql);
$this->idPrestaciones = mysql_insert_id($this->database->link);

}

// **********************
// UPDATE
// **********************

function update($id)
{



$sql = " UPDATE prestaciones SET  Titulo = '$this->Titulo',Icono = '$this->Icono',Link = '$this->Link',Orden = '$this->Orden' WHERE idPrestaciones = $id ";

$result = $this->database->query($sql);



}


} // class : end

?>
<!-- end of generated class -->
